global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'springboot'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8090
          - host.docker.internal:8082


